### ISSUE TITLE
Mejorar Header

### ISSUE THREAD

**Issue by jaenfigueroa** [Code-craft-studios/vigui#5]
## 📋 Subtareas

- [x] Cambiar el logo por el oficial
- [x] Implementar el nav en mobile
- [x] Cambiar por los colores del figma
