### ISSUE TITLE
Mejorar Footer

### ISSUE THREAD

**Issue by jaenfigueroa** [Code-craft-studios/vigui#6]
## 📋 Sub tareas

- [ ] Implementar google maps con la ubicacion real de la empresa
- [ ] Rellenar con la informacion real (Ubicacion, etc.)
- [x] Implementar los iconos de redes sociales
